import Vue from 'vue'
import {
  Button,
  Cell,
  CellGroup,
  Image,
  Row,
  Col,
  Popup,
  DatetimePicker,
  Field,
  Picker,
  Switch,
  SwitchCell,
  Uploader,
  Notify,
  Toast,
  Lazyload,
  List,
  Panel,
  Swipe,
  SwipeItem,
  Grid,
  GridItem,
  NavBar,
  Tabbar,
  TabbarItem,
  Area,
} from 'vant'

Vue.use(Button)
Vue.use(Cell).use(CellGroup)
Vue.use(Image)
Vue.use(Row).use(Col)
Vue.use(Popup)
Vue.use(DatetimePicker)
Vue.use(Field)
Vue.use(Picker)
Vue.use(Switch).use(SwitchCell)
Vue.use(Uploader)
Vue.use(Notify)
Vue.use(Toast)
Vue.use(Lazyload)
Vue.use(List)
Vue.use(Panel)
Vue.use(Swipe).use(SwipeItem)
Vue.use(Grid).use(GridItem)
Vue.use(NavBar)
Vue.use(Tabbar).use(TabbarItem)
Vue.use(Area)
